FilmProj/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/',include('django.conf.urls.i18n')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

urlpatterns+=i18n_patterns(
    path('accounts/',include('allauth.urls')),
    path('pages/',include('django.contrib.flatpages.urls')),
    path('contact/',include('Newsletter.urls')),
    path('',include('movies.urls')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path,include

from . import views

urlpatterns = [
    path('',views.MoviesView.as_view()),
    path('filter/',views.FilterMoviesView.as_view(),name='filter'),
    path('search/',views.SearchView.as_view(),name='search'),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    path('<slug:slug>/',views.MovieDetailView.as_view(),name='movie_detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
    path('actor/<str:slug>/',views.ActorView.as_view(),name='actor_detail'),
]

movies/models.py
from datetime import date

from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание",blank=True)
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Actor(models.Model):
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Актеры и режиссеры"
        verbose_name_plural = "Актеры и режиссеры"


class Genre(models.Model):
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание",blank=True)
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Movie(models.Model):
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default=0000)
    country = models.CharField("Страна", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name="режиссер", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="актеры", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="жанры")
    world_premiere = models.DateField("Премьера в мире", default=date.today)
    budget = models.PositiveIntegerField("Бюджет", default=0,
                                         help_text="указывать сумму в долларах")
    fees_in_usa = models.PositiveIntegerField("Сборы в США", default=0)
    fess_in_world = models.PositiveIntegerField("Сборы в мире", default=0)
    category = models.ForeignKey(
        Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True
    )
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={"slug": self.url})


    def get_review(self):
        return self.reviews_set.filter(parent__isnull = True)
    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class MovieShots(models.Model):
    title = models.CharField("Заголовок", max_length=100)
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"


class RatingStar(models.Model):
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм", related_name="ratings")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):

    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(Movie, verbose_name="фильм", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

movies/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

from .models import Rating, RatingStar, Reviews


class ReviewForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Reviews
        fields = ("name", "email", "text", "captcha")
        widgets = {
            "name": forms.TextInput(attrs={'placeholder':'Имя'}),
            "email": forms.EmailInput(attrs={'placeholder':'Email'}),
            "text": forms.Textarea(attrs={'required':True, 'cols':47, 'rows':5,'placeholder':'Содержание'})
        }


class RatingForm(forms.ModelForm):
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

movies/views.py
from django.db.models import Q
from .forms import RatingForm, ReviewForm
from django.views.generic import ListView, DetailView, View
from .models import *
from django.http import HttpResponseRedirect, HttpResponse


class GenreYear:
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        years_sorted_list = sorted(set(Movie.objects.filter(draft=False).values_list('year', flat=True)))
        return years_sorted_list


class MoviesView(GenreYear, ListView):
    paginate_by = 1
    model = Movie
    queryset = Movie.objects.filter(draft=False)


class MovieDetailView(GenreYear, DetailView):
    model = Movie
    slug_field = 'url'

    def get_context_data(self, **kwargs):
        context = super(MovieDetailView, self).get_context_data(**kwargs)
        context['star_form'] = RatingForm()
        context['form']=ReviewForm()
        return context


class AddReview(GenreYear, View):
    def post(self, request, pk):
        form  = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.movie = movie
            form.save()
        return HttpResponseRedirect(movie.get_absolute_url())


class ActorView(GenreYear, DetailView):
    model = Actor
    template_name = 'movies/actor.html'
    slug_field = "name"


class FilterMoviesView(GenreYear, ListView):
    paginate_by = 1

    def get_queryset(self):
        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre")) |
            Q(category__in=self.request.GET.getlist("category"))
        ).distinct().values("title", "tagline", "url", "poster")
        return queryset

    def get_context_data(self, **kwargs):
        context = super(FilterMoviesView, self).get_context_data(**kwargs)
        context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
        context["genre"] = ''.join([f"genre={x}&" for x in self.request.GET.getlist("genre")])
        context["category"] = ''.join([f"category={x}&" for x in self.request.GET.getlist("category")])
        return context


class AddStarRating(View):
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class SearchView(GenreYear, ListView):
    paginate_by = 4
    def get_queryset(self):
        title= self.request.GET.get("q")
        return Movie.objects.filter(title=title.capitalize())

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context["q"] = self.request.GET.get("q")
        return context

templates/movies/actor.html
{% extends 'main.html' %}
{%block title%}{{movie.name}}{%endblock%}
{%block content%}
{%load static%}
    <strong class="">Актеры и режиссеры</strong>
    <div class="row">
        <div class="col-xl-5 col-lg-6 mb-4 p-3">
            <img src="{{actor.image.url}}" width="400">
        </div>

        <div class="col-xl-7 col-lg-6">
            <h1>{{actor.name}}</h1>
            <div class="mb-4">
                    <h4>Информация о {{actor.name}}</h4>
                    <ul>
                        <li>
                            <span><b>Возраст: </b>{{actor.age}}</span>
                        </li>
                    </ul>
                    <ul>
                        {%if actor.film_director.all%}
                            <li>
                                <span><b>Режиссер:</b>
                                {% for movie in actor.film_director.all %}
                                    <a href="{{movie.get_absolute_url}}">
                                    {{ movie.title }}
                                    </a>
                                {% endfor %}
                                </span>
                            </li>
                        {%endif%}
                    </ul>
                    <ul>
                        {%if actor.film_actor.all%}
                            <li>
                                <span><b>Актер:</b></span>
                                {% for movie in actor.film_actor.all %}
                                    <a href="{{movie.get_absolute_url}}">
                                    {{ movie.title }}
                                    </a>
                                {% endfor %}
                            </li>
                        {%endif%}
                    </ul>
                <h4>О {{actor.name}}</h4>
    {{actor.description|safe}}
            </div>
        </div>
    </div>


{%endblock%}

templates/movies/movie_detail.html
{% extends 'main.html' %}
{% load static i18n %}
{%block title%}{{movie.title}}{%endblock%}
{%block style%}

{%endblock%}
{%block content%}
{%load static recaptcha3%}
    <link rel="stylesheet" href="{% static 'css/rating.css' %}" type="text/css" media="all">
    <div class="row">
        <div class="col-xl-3 col-lg-3 mb-4">
            <strong>{{movie.category}}</strong>
    <p>{{movie.tagline}}</p>
            <img src="{{movie.poster.url}}" width="230">
        </div>

        <div class="col-xl-6 col-lg-6">
            <h1>{{movie.title}}</h1>
            <div class="mb-4">
                    <h4>Информация о фильме</h4>
                    <ul>
                        <li>
                            <span><b>{% trans 'Год' %}:</b> {{ movie.year }}</span>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <span><b>{% trans 'Жанры' %}</b>{% for genre in movie.genres.all %}{{genre.name}} {% endfor %}</span>
                        </li>
                    </ul>
                    <ul>
                        <li>
                           <span><b>{% trans 'Страна' %}:</b> {{ movie.country }}</span>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <span><b>{% trans 'Премьера в мире' %}:</b>{{movie.world_premiere}}</span>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <span><b>{% trans 'Бюджет' %}:</b>{{movie.budget}}$</span>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <span><b>{% trans 'Сборы в США' %}</b>{{movie.fees_in_usa}}$</span>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <span><b>{% trans 'Сборы в мире' %}:</b>{{movie.fess_in_world}}$</span>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <form action="{% url 'add_rating' %}" method="post" name="rating">
                                <b>{%trans 'Рейтинг' %}:</b>
                                {% csrf_token %}
                                <input type="hidden" value="{{ movie.id }}" name="movie">
                                <span class="rating">
                                    {% for k, v in star_form.fields.star.choices %}
                                        <input id="rating{{ v }}" type="radio" name="star"
                                               value="{{ k }}">
                                        <label for="rating{{ v }}">{{ k }}</label>
                                    {% endfor %}
                                </span>
                                <span class="editContent">4.0</span>
                            </form>
                        </li>
                    </ul>

            </div>
        </div>

    </div>

    <h4>{%trans 'Описание'%}:</h4>{{movie.description|safe}}
    <h4>{% trans 'Режиссеры' %}</h4>
    <div class="md-4 row">
        {% for director in movie.directors.all %}
        <div class="col-xl-2 col-lg-2 col-md-2 mb-4">
            <a href="{{director.get_absolute_url}}" style="color:gray">
                <img class="bd-placeholder-img rounded-circle" width="100" height="100"  src="{{director.image.url}}">
                <h5>{{director.name}}</h5>
            </a>
        </div>
    </div>
    {% endfor %}
    <h4>{% trans 'Актеры' %}</h4>
    <div class="row ">

        {% for actor in movie.actors.all %}
            <div class="col-xl-2 col-lg-2 col-md-2 mb-4">
                <a href="{{actor.get_absolute_url}}" style="color:gray">
                    <img class="bd-placehold  er-img rounded-circle" width="100" height="100"  src="{{actor.image.url}}">
                    <h5>{{actor.name}}</h5>
                </a>
            </div>
        {% endfor %}
    </div>

    <div>
        <h4>{% trans 'Кадры из фильма'%}:</h4>
        {%for image in movie.movieshots_set.all%}
        <img src="{{image.image.url}}">
        {%endfor%}
    </div>
<h4>{%trans 'Оставить отзыв' %} </h4>
<form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
    {% csrf_token %}
    <input type="hidden" name="parent" id="contactparent" value="">
    <div class="md-10">
        {{ form.text }}
    </div>
    <div class="d-sm-flex">
        <div class=" p-0">
            {{ form.name }}
        </div>
        <div class=" ml-sm-3">
            {{ form.email }}
        </div>
        {{ form.captcha }}
    </div>
    <button type="submit" class="btn btn-secondary py-2 ">
        Отправить
    </button>
</form>
<div>
    <h4>{%trans 'Отзывы' %} </h4>
    {% for review in movie.get_review %}
            <div class="media py-1">
                <img src="{% static 'images/avatar_azamat.png' %}" class="mr-1 img-fluid" alt="image" width="60">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
                    <a href="#formReview"
                       onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                    {%for rew in review.reviews_set.all%}
                        <div class="media py-1">
                            <img src="{% static 'images/avatar_azamat.png' %}" class="mr-1 img-fluid" alt="image" width="60">
                            <div class="media-body mt-4">
                                <h5 class="mt-0 editContent">
                                    {{ rew.name }}
                                </h5>
                                <p class="mt-2 editContent">
                                    {{ rew.text }}
                                </p>
                            </div>
                    {%endfor%}
                </div>
            </div>
        {% endfor %}
</div>
</div>
    <script>
        function addReview(name, id) {
            document.getElementById("parent").value = id;
            document.getElementById("comment").innerText = `${name}, `
        }

    </script>
    <script src="{%static 'js/rating.js'%}"></script>
{%endblock%}

templates/movies/movie_list.html
{% extends 'main.html' %}
{% load static i18n %}
{% load i18n movie_tag %}
{%block title%}Главная{%endblock%}
{%block content%}
{%load static%}
{% load movie_tag %}
<div class="col-9 col-lg-9">
    <h2>{% trans 'Главная' %}</h2>
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-6 col-md-4 col-xl-3">
                    <div class=" text-center mt-lg-4">
                        <img src="/media/{{ movie.poster }}" class="img-fluid" width="230" alt="why">
                        <div class="">
                            <h4>
                                <a style="color:black" href="/{{ movie.url }}"
                                   class="editContent">
                                    {{ movie.title }}
                                </a>
                            </h4>

                            <div class="">
                                <div class="">
                                    <span class="">{{ movie.tagline }}</span>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="grid-img-right mt-4 text-right bg bg1">
            {% include 'pagination.html' %}
        </div>
    </div>
{%endblock%}

templates/movies/movies.html
{% extends 'main.html' %}
{%block title%}Главная{%endblock%}
{%block content%}
<div class=" col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4">
                    <div class=" text-center mt-lg-4">
                        <div class="">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="">
                            <h4>
                                <a style="color:black" href="{{ movie.get_absolute_url }}"
                                   class="editContent">
                                    {{ movie.title }}
                                </a>
                            </h4>

                            <div class="">
                                <div class="">
                                    <span class="">{{ movie.tagline }}</span>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
{%endblock%}